name: smart_hotel_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  flutter:
    sdk: flutter
  # State managment
  flutter_bloc: ^9.1.1
  # Work with bluetooth
  flutter_blue_plus: ^1.35.5
  # Work with svg icons
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-VariableFont_wght.ttf
