name: smart_hotel_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  # State managment
  flutter_bloc: ^9.1.1
  # Work with bluetooth
  flutter_blue_plus: ^1.35.5
  # Work with svg icons
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  protobuf: ^4.0.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner:
  json_serializable: ^6.9.5
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-VariableFont_wght.ttf
